/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(7A840816-DE01-491F-9BF8-E96839D54F5F)]
interface nsIInsecurePasswordNotification : nsISupports
{
    attribute AString offenderType;
    attribute AString offenderURL;

    void init(in AString offenderType, in AString offenderURL);
};

%{ C++
#define NS_INSECURE_PASSWORD_NOTIFICATION_CONTRACTID "@mozilla.org/insecurepassword/notification;1"
%}
