/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

native StringArray(const PRUnichar**);
/*
 * Holds localization message tag and message category
 * for security related console messages.
 */
[scriptable, uuid(FE9FC9B6-DDE2-11E2-A8F1-0A326188709B)]
interface nsISecurityConsoleMessage : nsISupports
{
  attribute AString lookupKey;
  attribute AString category;
  attribute StringArray params;
  attribute uint32_t paramsLength;
  attribute AString sourceLine;
  attribute AString sourceName;
  attribute uint32_t lineNumber;
  attribute uint32_t columnNumber;

  void init(in AString lookupKey, in AString category, in AString sourceLine,
            in AString sourceName, in uint32_t lineNumber,
            in uint32_t columnNumber, in StringArray params,
            in uint32_t paramsLength);
};

%{ C++
#define NS_SECURITY_CONSOLE_MESSAGE_CONTRACTID "@mozilla.org/securityconsole/message;1"
%}
